project:
  type: website
  output-dir: _site

website:
  title: "Amandeep Singh"

  navbar:
    pinned: true

    left:
      - href: index.qmd
        text: Home

      - href: pages/research.qmd
        text: Research

      - href: projects/index.qmd
        text: Projects

      - href: pages/publications.qmd
        text: Publications

      - href: pages/software.qmd
        text: Software

      - href: pages/teaching.qmd
        text: Teaching

      - href: pages/cv.qmd
        text: CV

      - href: pages/contact.qmd
        text: Contact

    #right:
      # Uncomment when ready
      # - icon: github
      #   href: https://github.com/AmandeepQLab
      #
      # - icon: google
      #   href: https://scholar.google.com/
      #
      # - icon: linkedin
      #   href: https://www.linkedin.com/
      #
      # - icon: envelope
      #   href: mailto:your.email@domain.com

  page-footer:
    left: |
      © 2026 Amandeep Singh
    right: |
      Built with Quarto using Quarto

format:
  html:
    theme: litera
    css: styles.css
    toc: false
    smooth-scroll: true
    page-layout: full

execute:
  freeze: auto